#!/bin/sh

OPTIONS='--no-run-if-empty' #option for xargs, do not run the command on empty input (not exists in BSD xargs)
echo | xargs $OPTIONS 2> /dev/null || OPTIONS='' #Try run xargs with $OPTIONS, erase OPTIONS on error

set -e
SRC='git diff --name-only --cached --diff-filter=AM'

echo '== Rubocop ===================================================================='
$SRC | grep '\.rb$' | xargs $OPTIONS rubocop --auto-correct
echo '== Rspec ======================================================================'
rspec
