default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: thinknetica
  password: thinknetica

development:
  <<: *default
  database: qa_development

test:
  <<: *default
  database: qa_test
